"""initial_schema_with_custom_difficulty

Revision ID: e81833419e8c
Revises:
Create Date: 2026-08-20 17:17:25.901211

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e81833419e8c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("problems", schema=None) as batch_op:
        batch_op.alter_column(
            "is_difficulty_customized",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("0"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("problems", schema=None) as batch_op:
        batch_op.alter_column(
            "is_difficulty_customized",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("0"),
        )

    # ### end Alembic commands ###
